# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make
builds:
  - id: kwt
    main: ./cmd/kwt
    binary: kwt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -mod=mod
  - id: kwtd
    main: ./cmd/kwtd
    binary: kwtd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -mod=mod
brews:
  - name: kwt
    repository:
      owner: bettercallshao
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/bettercallshao/kwt"
    description: "Run commands easily"
    install: |
      bin.install "kwt"
      bin.install "kwtd"
scoops:
  - repository:
      owner: bettercallshao
      name: scoop-bucket
    homepage: "https://github.com/bettercallshao/kwt"
    description: "Run commands easily"
    license: MIT
archives:
  - format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
