version: 2.1
jobs:
  sanity:
    docker:
    - image: circleci/golang:1.15
    steps:
    - checkout
    - run: make test
    - run: make
  release:
    docker:
    - image: circleci/golang:1.15
    steps:
    - checkout
    - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  sanity:
    jobs:
    - sanity:
        filters:
          branches:
            only: /.*/
          tags:
            ignore: /.*/
  release:
    jobs:
    - sanity:
        filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
          branches:
            ignore: /.*/
    - release:
        filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
          branches:
            ignore: /.*/
        requires:
        - sanity
